### PR TITLE
allow React 15 and update styles to comply with React 15

### PR DESCRIPTION
**Pull request by nikgraf**

### CODE REVIEW

**Comment by gaearon** [comment]
This repo uses semantic-release, would you mind amending your commit message to match it?

**Comment by nikgraf** [comment]
@gaearon ohh … done, let me know if (package, style) works. If not whats the convention? btw I probably add a contributors sections to the readme after this one :smile:

**Comment by nikgraf** [comment]
@gaearon can you make a new release on npm? see https://www.npmjs.com/package/redbox-react

**Comment by danmartinez101** [comment]
Looks like semantic-release opted not to ship a release because the label is "chore" I think only feat and fix result in releases?

**Comment by davidpfahler** [comment]
Sorry everyone, please see https://github.com/KeywordBrain/redbox-react/issues/50. It's now released.

**Pull request merged**
