### PR TITLE
Update examples to react 14

### LINKED ISSUE #29: 0.14 support?
I'm preparing to upgrade to react 0.14 from 0.14-rc1. All other components I'm using (react-router, react-bootstrap, etc...) have all upgrade to 0.14. Redbox is the last one. Any idea if/when it would be upgraded?

### PR DESCRIPTION
**Pull request by colinmeinke**
- Updated `react-transform-catch-errors` to use react 14.
- Removed `babel-plugin-react-hot` example as `babel-plugin-react-hot` is depreciated.
- Removed `react-hot-loader-example` example as `react-hot-loader` is depreciated.

**Note:** This pull request is based off of, and therefore includes, my [babel 6 pull request](https://github.com/KeywordBrain/redbox-react/pull/42).

Closes #29.

### CODE REVIEW

**Comment by colinmeinke** [comment]
@davidpfahler could you try clearing the travis `node_modules` cache and rerunning this test? Same issue with #42

**Comment by gaearon** [comment]
I'd say `react-hot-loader` is still alive despite being deprecated, so I'd like to keep this example.

**Comment by colinmeinke** [comment]
@gaearon no problem, I've re-added and updated `react-hot-loader-example` to 14.x, however, although the hot reloading is working it is not displaying redbox on error. Any ideas?

**Comment by davidpfahler** [comment]
@colinmeinke I'm sorry, but I never had this problem before. How can I flush the node_modules cache in travis? Couldn't find anything about that functionality.

**Comment by colinmeinke** [comment]
@davidpfahler try this https://docs.travis-ci.com/user/caching/#Clearing-Caches ?

**Comment by davidpfahler** [comment]
@colinmeinke I cleared the cache and reran your PR.

**Comment by davidpfahler** [comment]
@colinmeinke Sorry for not using your work here. I had to dig through this myself, because it was entangled with some other stuff I wanted to bring to the examples. I would very much appreciate it, if you could join the discussion on [this PR](https://github.com/KeywordBrain/redbox-react/pull/59) and possibly review my changes. Most of this is in anticipation of [react-hot-loader 3](https://github.com/gaearon/react-hot-loader/pull/240).

**Pull request closed without merging**
