### PR TITLE
Document the style prop

### PR DESCRIPTION
**Pull request by glenjamin**
As discussed in #44

### CODE REVIEW

**Comment by davidpfahler** [comment]
@glenjamin Thanks! Just one thing: Why did you delete the css file? Was that on purpose?

**Comment by glenjamin** [comment]
Oh, it was - but I probably shouldn't have included that in this PR.

As far as I can tell, the CSS file isn't used anymore.

**Comment by davidpfahler** [comment]
@glenjamin Alright, if so, we should get rid off it. I'm just not into the code right now.

**Comment by davidpfahler** [comment]
@glenjamin Could you please update this PR so it's in sync with master again? If it's not too much to ask, could you also please change your commit message to something like `doc: ...`.

**Comment by glenjamin** [comment]
@davidpfahler done :ship:

**Pull request merged**
