### PR TITLE
Add style options

### PR DESCRIPTION
**Pull request by brenoc**
Depends on: https://github.com/gaearon/react-transform-catch-errors/pull/8

### CODE REVIEW

**Comment by gaearon** [comment]
FYI gaearon/react-transform-catch-errors#8 is out as 0.2.0

**Comment by brenoc** [comment]
Example of a reporterOptions file:

```js
module.exports = {
  style: {
    redbox: {
      boxSizing: 'border-box',
      fontFamily: 'sans-serif',
      padding: 10,
      top: 0,
      left: 0,
      bottom: 0,
      right: 0,
      width: '100%',
      background: 'rgb(204, 0, 0)',
      color: 'white',
      zIndex: 9999,
      textAlign: 'left',
      fontSize: '16px',
      lineHeight: 1.2
    }
  }
};
```

**Comment by davidpfahler** [comment]
@brenoc Hi and thank you very much for your contribution. Do you think you could add an example for react-transform-catch-errors to the `examples` folder?

**Comment by brenoc** [comment]
@davidpfahler you're welcome! There you go with the react-transform-catch-errors example.

**Comment by davidpfahler** [comment]
@brenoc Thank you very much!

**Pull request merged**
