### PR TITLE
Support for Safari

### PR DESCRIPTION
**Pull request by danmartinez101**
Fixes https://github.com/KeywordBrain/redbox-react/issues/8

### CODE REVIEW

**Comment by mxstbr** [comment]
Will this be merged soon?

**Comment by gaearon** [comment]
Sorry for the delays. Thanks for the PR. There's quite a bit of unrelated stuff here so I'm going to cherry-pick some of these changes by hand, and make other changes on my own.

**Comment by danmartinez101** [comment]
Sorry, I thought that including the other pull requests and fixing the issues that had blocked them from being merged initially was a good thing. 

If you'd like me to create a PR with just the minimal changes to guard against the error in safari, I can do that too.

Should I close this PR?

**Comment by gaearon** [comment]
That would be helpful, yes. As you see this repo follows semantic-release commit message conventions. Can you please take a look at those? The commit messages are significant because they're parsed by semantic-release which is another reason this PR is a bit of a pain to merge.

**Comment by danmartinez101** [comment]
Thanks for helping me out with this, I'm still pretty new to open source and all :D

I reused this PR and updated the description. 
I think I got the commit message in the right format, but if there are still issues I'm happy to update it. 

semantic-release looks really useful!

You mentioned some other changes you want to make; I'm also happy to help implement any of those changes if you'd like (and if they are within my abilities).

**Comment by danmartinez101** [comment]
@gaearon Is there anything else I should do here or is it just down to whenever you have time free to merge and release?

(no rush, just want to make sure I don't need to do more with this)

**Comment by gaearon** [comment]
This looks good. I'll merge today or tomorrow.

**Comment by danmartinez101** [comment]
@davidpfahler Is this PR in need of anything in order to be merged?

**Comment by davidpfahler** [comment]
@gaearon had his eye on this one. I have honestly not looked at this PR, yet.

**Comment by danmartinez101** [comment]
Thanks!

**Comment by gaearon** [comment]
I really dropped the ball with taking so long to merge this one. Sorry!

**Comment by danmartinez101** [comment]
No worries, everyone's busy!

**Pull request merged**
