### PR TITLE
Updates node react 0.14

### PR DESCRIPTION
**Pull request by eelcocramer**
See discussion in #29

### CODE REVIEW

**Comment by davidpfahler** [comment]
@eelcocramer First thing I noticed is that you upgraded the examples to 0.14 as well. If this is necessary, this is a breaking change. Just need to make sure to declare that correctly.

**Comment by eelcocramer** [comment]
Not sure it is necessary but I guess the imports should mimic the import from the main module: `>=0.13.2 || ^0.14.0` so things are consistent.

Better yet, [ditch these dependencies all together and just load the same version of react the module uses](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders)

**Comment by eelcocramer** [comment]
Ok, I removed the dependencies like I mentioned above. I've tried to run the `react-hot-loader-example` with both react 0.13 and 0.14 and it runs ok.

I'm not sure how to run the other examples.

**Comment by palmdeezy** [comment]
lgtm

**Comment by davidpfahler** [comment]
@eelcocramer Thanks again for your good work here. I had some time to test this and it seems all examples work just fine, except the react-transform-catch-errors. I'm getting

`Uncaught ReferenceError: _ReactTemp is not defined`

when running this examples (`npm start`) ==> `http://localhost:3000`. Not sure what's going on here, but I though you might have an idea.

**Comment by eelcocramer** [comment]
I'll take a look next week.

**Comment by eelcocramer** [comment]
Can't find a quick fix for this. It is [this line](https://github.com/KeywordBrain/redbox-react/blob/master/examples/react-transform-catch-errors/components/App.js#L1) that causes the exception.

**Pull request closed without merging**
