### PR TITLE
Update redbox to take over entire screen

### PR DESCRIPTION
**Pull request by amccloud**
Not sure what the intended behavior is but currently the redbox displays awkwardly.

### CODE REVIEW

**Comment by suevalov** [comment]
My vote goes to this one. `z-index` should be increased.

**Comment by dallonf** [comment]
+1, was just about to submit this myself.

**Comment by amccloud** [comment]
@davidpfahler Can you take a look at this?

**Comment by sgwilym** [comment]
Damn, was just about to make this easy PR! This would be cool!

**Comment by davidpfahler** [comment]
Thank you @amccloud and all others who asked for this fix. This should be fixed in the latest release. Please ping me here if not. Sorry, I couldn't merge your PR, @amccloud, but we had to move to style attributes.

**Comment by amccloud** [comment]
@davidpfahler No problem. I'm curious, why did you move away from css-modules?

**Comment by davidpfahler** [comment]
@amccloud It caused some issues: #11

**Pull request closed without merging**
