### PR TITLE
Use ReactDOM.render instead of Render (README)

### PR DESCRIPTION
**Pull request by sunyang713**

### CODE REVIEW

**Comment by gaearon** [comment]
Dang, I forgot this project is using semantic-release. I wonder what happens now :fearful:

**Comment by danmartinez101** [comment]
@gaearon pretty sure all it takes  is a rebase(reword commit) and then force push and it will build / publish the new version

**Comment by gaearon** [comment]
I just tried force pushing but `! [remote rejected] master -> master (protected branch hook declined)`

**Comment by gaearon** [comment]
All right, I removed protection, force-pushed, and added protection again. Seems to work.

**Comment by davidpfahler** [comment]
@gaearon Sorry for the late reply, but I guess what you did is the only solution in this circumstance. In an ideal world, there'd be a hook to check if commit message conventions were adhered to.
/cc @boennemann

**Pull request merged**
